#!/bin/bash -x 

set -x

NPS_VERSION=1.9.32.1

UBUNTU_VERSION=`lsb_release -c | cut -f2`

sudo apt-get install build-essential -y
sudo apt-get build-dep nginx -y
sudo apt-get install dpkg-dev build-essential zlib1g-dev libpcre3 libpcre3-dev git unzip libssl-dev -y

wget -N http://nginx.org/keys/nginx_signing.key
sudo apt-key add nginx_signing.key
rm nginx_signing.key

# add nginx to sources
echo "deb http://nginx.org/packages/ubuntu/ ${UBUNTU_VERSION} nginx" | sudo tee /etc/apt/sources.list.d/nginx.list
echo "deb-src http://nginx.org/packages/ubuntu/ ${UBUNTU_VERSION} nginx" | sudo tee -a /etc/apt/sources.list.d/nginx.list

# update list of packages
sudo apt-get update

# build dir
rm -rf ~/ngx_build
mkdir ~/ngx_build
cd ~/ngx_build

# install any packages needed for nginx
sudo apt-get build-dep nginx -y

apt-get source nginx
NGINX_VER=$(find ./nginx* -maxdepth 0 -type d | sed "s|^\./||")
NGINX_BUILD_DIR=~/ngx_build/$NGINX_VER

echo "Using nginx ${NGINX_VER}"

# can edit debian/rules for your modules
# here we use sed to add the geoip module
#sed -i '/--with-http_sub_module \\/i--with-http_geoip_module \\' $NGINX_BUILD_DIR/debian/rules

# create a modules dir to hold the pagespeed module
mkdir $NGINX_BUILD_DIR/modules
cd $NGINX_BUILD_DIR/modules

# steps from https://github.com/pagespeed/ngx_pagespeed
# download pagespeed
wget https://github.com/pagespeed/ngx_pagespeed/archive/release-${NPS_VERSION}-beta.zip
unzip release-${NPS_VERSION}-beta.zip
cd ngx_pagespeed-release-${NPS_VERSION}-beta/
wget https://dl.google.com/dl/page-speed/psol/${NPS_VERSION}.tar.gz
tar -xzvf ${NPS_VERSION}.tar.gz  # extracts to psol/

# now enable pagespeed module in debian/rules
sed -i "s/\.\/configure /.\/configure --add-module=modules\/ngx_pagespeed-release-${NPS_VERSION}-beta /g" $NGINX_BUILD_DIR/debian/rules

# build deb
cd $NGINX_BUILD_DIR
dpkg-buildpackage -b

# debs should be in ~/ngx_build

