#!/bin/bash

# This script builds a nginx deb with pagespeed
# but the deb doesn't contain any init scripts

set -ex

# get version from env or use default
NPS_VERSION=${NPS_VERSION:-1.12.34.2}
NGINX_VERSION=${NGINX_VERSION:-1.11.8}
OPENSSL_VERSION=${OPENSSL_VERSION:-1.0.2j}

echo "Building ngx_pagespeed ${NPS_VERSION}"

UBUNTU_VERSION=`lsb_release -c | cut -f2`

PS_NGX_EXTRA_FLAGS="--with-cc=/usr/lib/gcc-mozilla/bin/gcc"
LD_OPTS="-Wl,-z,relro -Wl,--as-needed -static-libstdc++"
CC_OPTS="-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2"

sudo apt-get install build-essential -y
sudo apt-get install dpkg-dev build-essential zlib1g-dev libpcre3 libpcre3-dev unzip checkinstall -y


# build dir
get_abs_filename() {
  # $1 : relative filename
  echo "$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"
}
NGX_BUILD=$(get_abs_filename "./ngx_build")

cd $NGX_BUILD

wget http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz
tar zxf nginx-${NGINX_VERSION}.tar.gz

wget https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz
tar zxf openssl-${OPENSSL_VERSION}.tar.gz

# steps from https://github.com/pagespeed/ngx_pagespeed
# download pagespeed
wget https://github.com/pagespeed/ngx_pagespeed/archive/v${NPS_VERSION}-beta.zip
unzip v${NPS_VERSION}-beta.zip
cd ngx_pagespeed-${NPS_VERSION}-beta/
psol_url=https://dl.google.com/dl/page-speed/psol/${NPS_VERSION}.tar.gz
[ -e scripts/format_binary_url.sh ] && psol_url=$(scripts/format_binary_url.sh PSOL_BINARY_URL)
wget ${psol_url}
tar -xzvf $(basename ${psol_url})  # extracts to psol/
cd ..

cd nginx-${NGINX_VERSION}
./configure \
	--user=nginx \
	--group=nginx \
	 --prefix=/etc/nginx \
--sbin-path=/usr/sbin/nginx \
--conf-path=/etc/nginx/nginx.conf \
--error-log-path=/var/log/nginx/error.log \
--http-log-path=/var/log/nginx/access.log \
--pid-path=/var/run/nginx.pid \
--lock-path=/var/run/nginx.lock \
--http-client-body-temp-path=/var/cache/nginx/client_temp \
--http-proxy-temp-path=/var/cache/nginx/proxy_temp \
--http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
--http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \
--http-scgi-temp-path=/var/cache/nginx/scgi_temp \
--with-cc-opt="${CC_OPTS}" \
--with-ld-opt="${LD_OPTS}" \
	--add-module=../ngx_pagespeed-${NPS_VERSION}-beta \
	${PS_NGX_EXTRA_FLAGS} \
	--with-openssl=../openssl-${OPENSSL_VERSION} \
	--with-http_ssl_module \
	--with-http_v2_module \
	--with-http_stub_status_module \
	--with-http_realip_module

make

sudo checkinstall -D --install=no -y --pkgversion="${NGINX_VERSION}-ps-${NPS_VERSION}" make install
sudo rm -rf doc-pak
mv *.deb $NGX_BUILD/
